import { GetServerSideProps } from 'next';
import Head from 'next/head'
import Image from 'next/image'
import { FormEvent, useContext, useState } from 'react';
import { AuthContext } from '../contexts/AuthContext';
import styles from '../styles/Home.module.css'
import { parseCookies } from 'nookies'
import { withSSRGuest } from '../utils/withSSRGuest';


export default function Home() {

  const [email, setEmail] = useState<string>();
  const [password, setPassword] = useState<string>();

  const { signIn } = useContext(AuthContext);

  async function handleSubmit(event: FormEvent) {
    event.preventDefault();
    const data = {
      email,
      password,
    }
    await signIn(data);
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <form
        className={styles.main}
        onSubmit={handleSubmit}
      >
        <input
          type="email"
          className={styles.inputField}
          value={email}
          onChange={event => setEmail(event.target.value)}
        />

        <input
          type="password"
          className={styles.inputField}
          value={password}
          onChange={event => setPassword(event.target.value)}
        />

        <button type="submit" className={styles.formButton}>Login</button>
      </form>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}


export const getServerSideProps = withSSRGuest(async (ctx) => {
  return {
    props: {}
  };
});
